### ISSUE TITLE
boom incompatibility

### ISSUE THREAD

**Issue by laurentdutheil** [Pranay92/hapi-next#4]
Our project is already using boom.
But when we do a reply.next(boom.notFound('Unknown product')), we end up with the default 400 error and not the boom one.

Could you handle the boom error merge ?

**Comment by Pranay92** [comment]
This will be a feature request since as of now we're not supporting much options for reply.next(err). Till this feature is implemented and tested, I would suggest you to use the following as a workaround:

````reply.next({status : 404, message : 'Unknown product' });````

OR  

you can override the boom.notFound function to the following:

````
boom.notFound = function(msg) {
  return {status : 404, message : msg};
}
````

and then once hapi.next(err) supports directly consuming the boom object, you can simply remove the overriden function without needing to update the reply.next in multiple places.

**Comment by laurentdutheil** [comment]
That was fast !
Thank you !
